### ISSUE TITLE
About downloading the datasets

### ISSUE THREAD

**Issue by pkqbajng** [facebookresearch/OrienterNet#11]
Hi, sir, thanks for your excellent job. When I download the MGL and the kitti dataset, the process bar keeps stable as follows. Could you please offer a google link or other simple way to download the datasets?
![image](https://github.com/facebookresearch/OrienterNet/assets/94164222/cc168abb-deee-4f9c-8690-a60e4d3a6808)
![image](https://github.com/facebookresearch/OrienterNet/assets/94164222/f6f65717-4ef3-46a9-83c0-699e4ff871ca)

**Comment by Skydes** [comment]
This is odd.
- For KITTI: Can you check that the file is accessible by visiting the URL printed in the console? What versions of `requests` and `tqdm` are you using?
- For MGL: Can you print the URL and check that it is accessible for a few images?
https://github.com/facebookresearch/OrienterNet/blob/213aff45ce49a6aea11d273d198d9c2969457e10/maploc/data/mapillary/download.py#L65-L69

**Comment by pkqbajng** [comment]
> This is odd.
> 
> * For KITTI: Can you check that the file is accessible by visiting the URL printed in the console? What versions of `requests` and `tqdm` are you using?
> * For MGL: Can you print the URL and check that it is accessible for a few images?
>   https://github.com/facebookresearch/OrienterNet/blob/213aff45ce49a6aea11d273d198d9c2969457e10/maploc/data/mapillary/download.py#L65-L69

Thanks, I got it, I can download the datasets by copy the link to my browser

**Comment by Timber-Ye** [comment]
> > This is odd.
> > 
> > * For KITTI: Can you check that the file is accessible by visiting the URL printed in the console? What versions of `requests` and `tqdm` are you using?
> > * For MGL: Can you print the URL and check that it is accessible for a few images?
> >   https://github.com/facebookresearch/OrienterNet/blob/213aff45ce49a6aea11d273d198d9c2969457e10/maploc/data/mapillary/download.py#L65-L69
> 
> Thanks, I got it, I can download the datasets by copy the link to my browser My questions have been solved, so I close this issue, best wishes to your following jobs.

I'm also running into this issue when downloading MGL with the file accessible via the URL. Could you kindly share the solution?
