### ISSUE TITLE
About adapting the map crop size

### ISSUE THREAD

**Issue by Zhenghao97** [facebookresearch/OrienterNet#25]
Hello Sarlin,

The city's content which I use is very sparse such like buildings, etc.
I have to enlarge the map size to contain more content to assist localization.
So If I adapt map crop size, like 64 to 96, which other params also need to adapt?

Looking forward your reply, thanks!

**Comment by sarlinpe** [comment]
Given 
https://github.com/facebookresearch/OrienterNet/blob/5f0d2d4ac27daa4319f9a6b30cec434303aa1a35/maploc/conf/data/mapillary.yaml#L30-L31

https://github.com/facebookresearch/OrienterNet/blob/5f0d2d4ac27daa4319f9a6b30cec434303aa1a35/maploc/conf/orienternet.yaml#L10-L11

- You want `crop_size_meters = 96`
- You can update `max_init_error ~ crop_size_meters - z_max/2 = 80` to make the training more difficult
- If objects are sparse, you could increase `z_max` to 48.

All of this will increase the GPU memory requirement. A trade-off between size and accuracy is to decrease `pixel_per_meter`, e.g. to 1?

**Comment by hanxjing** [comment]
@sarlinpe 
Hi Sarlin,

According to the [paper](https://arxiv.org/pdf/2304.02009.pdf),

> we render maps W×H=128×128m centered around points randomly sampled within **32m** of the GT pose.

But in [OrienterNet/maploc/conf/data/mapillary.yaml](https://github.com/facebookresearch/OrienterNet/blob/5f0d2d4ac27daa4319f9a6b30cec434303aa1a35/maploc/conf/data/mapillary.yaml#L30-L31),

> max_init_error: 48

Is the 32 meters in the paper set using max_init_error?
Is the max_init_error used in the training on MGL 48 meters?

Thanks!
