### ISSUE TITLE
Error regarding ReadTimeout occured while preparing MGL dataset

### ISSUE THREAD

**Issue by culigan3186** [facebookresearch/OrienterNet#32]
Hi, 

Thank you for the great work. 
I just had a small question about downloading MGL dataset. I keep getting the following error while running the code to download the Mapillary Geo-Localization dataset.
Errors such as asyncio.exceptions.CancelledError, TimeoutError, and httpcore.ReadTimeout keep occurring.

This is the code I executed   **python -m maploc.data.mapillary.prepare --token "my_token"**

In my case, I am using a clone of the most recent version of OrienterNet. Exactly, I am using Bugfixes when preparing the Mapillary dataset(#29) commit.

Could you please let me know if there is anything I missed or need to fix while downloading the dataset?

![image](https://github.com/facebookresearch/OrienterNet/assets/67793181/91698067-267b-4127-b69d-374344b83954)

![image](https://github.com/facebookresearch/OrienterNet/assets/67793181/dcced6a3-2766-4caa-a831-dcbaa9a1b0aa)

**Comment by culigan3186** [comment]
okay. This is my full stack trace.

![image](https://github.com/facebookresearch/OrienterNet/assets/67793181/2e116a0f-0a56-47b2-9527-16ce6cbbbdfd)
![image](https://github.com/facebookresearch/OrienterNet/assets/67793181/7e9021b3-dd3c-4df3-80d9-4785f9bc5474)

**Comment by culigan3186** [comment]
Thank you very much for your help. The method you gave me worked. However, the following error occurred. I think it's most likely a problem with my internet connection like you said.
![image](https://github.com/facebookresearch/OrienterNet/assets/67793181/6e08f219-427a-496a-a05a-b3c61e22afbd)
![image](https://github.com/facebookresearch/OrienterNet/assets/67793181/7a49317b-c050-4330-b35f-bc16a3f742a4)

**Comment by sarlinpe** [comment]
Can you try PR https://github.com/facebookresearch/OrienterNet/pull/33? does it help?

**Comment by sarlinpe** [comment]
Great! FYI you can pass a tuple of exceptions:
```diff
-    @retry(times=5, exceptions=httpx.RemoteProtocolError)
+    @retry(times=5, exceptions=(httpx.RemoteProtocolError, httpx.ReadError))
```
