### ISSUE TITLE
Tensor with 0 values after rectification when trying demo

### ISSUE THREAD

**Issue by d4n3x** [facebookresearch/OrienterNet#35]
Hello @all,

I have the problem that i cannot successfully run the demo. As I investigated the problem it seems to be a problem with the **rectify_image**. The image thensor has reasonable values before this step but if I step over this step the tensor has all zeros.

`   rectified = torch.nn.functional.grid_sample(
        image[None],
        grid_norm[None],
        align_corners=False,
        mode="bilinear"
    ).squeeze(0)`
    
  Rectified then only is returned as `tensor([[[0., 0., 0.,  ..., 0., 0., 0.]`
  
  My system runs macOS 13 Ventura with a M1 chip.
  
  Any ideas what could goes wrong here?

**Comment by sarlinpe** [comment]
Can you reproduce this with a minimal synthetic example? does this occur with different versions of PyTorch?

**Comment by d4n3x** [comment]
The PyTorch version used is the 2.1.0 stable release. As of different versions i have to try...

**Comment by d4n3x** [comment]
> Can you reproduce this with a minimal synthetic example? does this occur with different versions of PyTorch?

It seems that grid_sample is not the problem as it seems to work in a minimal example. Is there a dockerized version of this code to test since maybe a version is still the problem?

**Comment by d4n3x** [comment]
@sarlinpe 

Regardless what I tried (also a windows machine, etc.) I get the following output and I am quite clueless about it. Any help is appreciated.

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[19], line 9
      6 from maploc.utils.viz_2d import features_to_RGB
      8 # Run the inference
----> 9 uv, yaw, prob, neural_map, image_rectified = demo.localize(
     10     image, camera, canvas, roll_pitch=gravity)
     12 # Visualize the predictions
     13 overlay = likelihood_overlay(prob.numpy().max(-1), map_viz.mean(-1, keepdims=True))

File [~/Documents/1_Private/0_University/Masterarbeit/Repositories/orienterNet/OrienterNet/maploc/demo.py:191](https://file+.vscode-resource.vscode-cdn.net/Users/daniel.kreuzer/Documents/1_Private/0_University/Masterarbeit/Repositories/orienterNet/OrienterNet/~/Documents/1_Private/0_University/Masterarbeit/Repositories/orienterNet/OrienterNet/maploc/demo.py:191), in Demo.localize(self, image, camera, canvas, **kwargs)
    190 def localize(self, image: np.ndarray, camera: Camera, canvas: Canvas, **kwargs):
--> 191     data = self.prepare_data(image, camera, canvas, **kwargs)
    192     data_ = {k: v.to(self.device)[None] for k, v in data.items()}
    193     with torch.no_grad():

File [~/Documents/1_Private/0_University/Masterarbeit/Repositories/orienterNet/OrienterNet/maploc/demo.py:172](https://file+.vscode-resource.vscode-cdn.net/Users/daniel.kreuzer/Documents/1_Private/0_University/Masterarbeit/Repositories/orienterNet/OrienterNet/~/Documents/1_Private/0_University/Masterarbeit/Repositories/orienterNet/OrienterNet/maploc/demo.py:172), in Demo.prepare_data(self, image, camera, canvas, roll_pitch)
    165     roll, pitch = roll_pitch
    166     image, valid = rectify_image(
    167         image,
    168         camera.float(),
    169         roll=-roll,
    170         pitch=-pitch,
    171     )
--> 172 image, _, camera, *maybe_valid = resize_image(
...
   3927             )
   3928     output_size = size
   3929 else:

TypeError: expected size to be one of int or Tuple[int] or Tuple[int, int] or Tuple[int, int, int], but got size with types [, ]`

**Comment by d4n3x** [comment]
Fixed with [https://github.com/facebookresearch/OrienterNet/pull/37](#37). Thanks :)
