### ISSUE TITLE
a question about the demo

### ISSUE THREAD

**Issue by SWQN2** [facebookresearch/OrienterNet#36]
Hi Sarlin:
I'm trying to use the demo on the Google colab.
When i try to run the "Localize!" part , a error occurs.
![Screenshot from 2023-10-31 20-00-40](https://github.com/facebookresearch/OrienterNet/assets/138971903/617cd570-7ef0-4940-b7ee-09b2ea0cc97c)

could  you please help me with that?
Thanks.

**Comment by d4n3x** [comment]
Same problem over here....

**Comment by sarlinpe** [comment]
Thanks for reporting this. Fixed in https://github.com/facebookresearch/OrienterNet/pull/37
