### ISSUE TITLE
Question about sample_xyz

### ISSUE THREAD

**Issue by jike5** [facebookresearch/OrienterNet#42]
hi sarlinpe，
Thank you for your excellent work! I noticed that in the sample_xyz function, you concatenate the angle and xy_grid, resulting in grid_norm containing an index of (angle, x, y). 

https://github.com/facebookresearch/OrienterNet/blob/38e60a1160925b099ac2f521ef699f52f53e236b/maploc/models/voting.py#L136

However, the last three dimensions in volume_padded are (x, y, angle), for you change the channel from (B,N,H,W) to (B,H,W,N) in the line below, it seems to be inconsistent.

https://github.com/facebookresearch/OrienterNet/blob/38e60a1160925b099ac2f521ef699f52f53e236b/maploc/models/orienternet.py#L147

Could you please confirm if this is a mistake?

Thank you!

**Comment by jike5** [comment]
> hi sarlinpe， Thank you for your excellent work! I noticed that in the sample_xyz function, you concatenate the angle and xy_grid, resulting in grid_norm containing an index of (angle, x, y).
> 
> https://github.com/facebookresearch/OrienterNet/blob/38e60a1160925b099ac2f521ef699f52f53e236b/maploc/models/voting.py#L136
> 
> However, the last three dimensions in volume_padded are (x, y, angle), for you change the channel from (B,N,H,W) to (B,H,W,N) in the line below, it seems to be inconsistent.
> 
> https://github.com/facebookresearch/OrienterNet/blob/38e60a1160925b099ac2f521ef699f52f53e236b/maploc/models/orienternet.py#L147
> 
> Could you please confirm if this is a mistake?
> 
> Thank you!

I used F.grid_sample() to do some testing, and it seems that the xyz coordinates in the grid correspond to the -3, -2, -1 dimensions of the input. So it makes sense in your code to place the angle at the beginning.

**Comment by sarlinpe** [comment]
The API of `grid_sample` is indeed confusing. Glad that you figured it out!
