### ISSUE TITLE
build error of sphinx

### ISSUE THREAD

**Issue by gujiaqivadin** [facebookresearch/OrienterNet#5]
After I run this 
`python -m pip install -r requirements/full.txt`

And I get this output:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sphinx.setup_command'
```

But I have already install the sphinx, can you tell me how to fix the error.

**Comment by Skydes** [comment]
Thank you for reporting this. I cannot help without more details - can you please report here the entire error logs?

**Comment by gujiaqivadin** [comment]
I think the problem is on the installing of openSfm, the"git+https://github.com/mapillary/OpenSfM" line in the full.txt, 

After I run 
`python -m pip install -r requirements/full.txt`

I got the error with:

```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/mapillary/OpenSfM (from -r requirements/full.txt (line 17))
  Cloning https://github.com/mapillary/OpenSfM to /tmp/pip-req-build-826ikhu_
  Running command git clone --filter=blob:none --quiet https://github.com/mapillary/OpenSfM /tmp/pip-req-build-826ikhu_
  Resolved https://github.com/mapillary/OpenSfM to commit a1f1959806039d1dfbd9436a95b1837360a7f9f1
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-826ikhu_/setup.py", line 9, in <module>
          from sphinx.setup_command import BuildDoc
      ModuleNotFoundError: No module named 'sphinx.setup_command'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by gujiaqivadin** [comment]
> Thank you for reporting this. I cannot help without more details - can you please report here the entire error logs?

I think the problem is on the installing of openSfm, the"git+https://github.com/mapillary/OpenSfM" line in the full.txt, 

After I run 
`python -m pip install -r requirements/full.txt`

I got the error with:

```
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/mapillary/OpenSfM (from -r requirements/full.txt (line 17))
  Cloning https://github.com/mapillary/OpenSfM to /tmp/pip-req-build-826ikhu_
  Running command git clone --filter=blob:none --quiet https://github.com/mapillary/OpenSfM /tmp/pip-req-build-826ikhu_
  Resolved https://github.com/mapillary/OpenSfM to commit a1f1959806039d1dfbd9436a95b1837360a7f9f1
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-826ikhu_/setup.py", line 9, in <module>
          from sphinx.setup_command import BuildDoc
      ModuleNotFoundError: No module named 'sphinx.setup_command'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by Skydes** [comment]
What happens if you manually clone and build OpenSfM following [the official instructions](https://opensfm.org/docs/building.html)?

**Comment by gujiaqivadin** [comment]
> What happens if you manually clone and build OpenSfM following [the official instructions](https://opensfm.org/docs/building.html)?

The problem is sovled, thx for your reply. The main reason is the wrong version of sphinx.

**Comment by zhxyuuu** [comment]
> 
Hello, I encountered the same issue while configuring the environment. May I ask which version of Sphinx you used to resolve the problem? Thank you.

**Comment by zhxyuuu** [comment]
> > What happens if you manually clone and build OpenSfM following [the official instructions](https://opensfm.org/docs/building.html)?
> 
> The problem is sovled, thx for your reply. The main reason is the wrong version of sphinx.

Hello, I encountered the same issue while configuring the environment. May I ask which version of Sphinx you used to resolve the problem? Thank you.

**Comment by dizzyrue** [comment]
> What happens if you manually clone and build OpenSfM following [the official instructions](https://opensfm.org/docs/building.html)?

i encountered the same issue,did you solve it ? thank you!
