### ISSUE TITLE
Error in demo.localize output

### ISSUE THREAD

**Issue by MatteoT90** [facebookresearch/OrienterNet#9]
Hi. Thanks for the great work!!! 
I was trying to run orienternet/maploc/demo.py and there seemed to be something wrong about the returned yaw. 

Looking at the output of the ``localize'' function, at line 211, it seems there is a small bug, so it is returning the scaled longitude instead of the yaw:
   return xyr[:2], xyr[1], prob, neural_map, data["image"]
while it should probably be:
   return xyr[:2], xyr[2], prob, neural_map, data["image"].

Other than this, this project looks great =)

**Comment by Skydes** [comment]
Oof nice catch, thank you! Fixed in https://github.com/facebookresearch/OrienterNet/commit/e8109275aa511a667237186d344459869e03dc9d.
